### ISSUE TITLE
How to manage game

### ISSUE THREAD

**Issue by shinjawkwang** [EherSenaw/HalliGalli_JAVA#16]
1. A player shouldn't be able to flip card when it is opposite's turn
2. When player hit bell on wrong time, the player should give a card to opposite (or do nothing, if we don't have enough time)
3. When player hit bell on right time, the opposite should give the card from deck.cards from 0 to topIdx (implemented on Deck.mergeDeck)
4. when a player's deck is empty, close the game.
5(optional). display player's(only player1) numbers of remained cards

**Comment by EherSenaw** [comment]
I had some improvements in processing multithread server, checkout commits, plz.
I'm considering: //TODO: Displaying GUI seprately for each players
